# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07aa4c4255c96f9028b777936ca73b31b81f128e3f38f0a7524a4a2aec5b46a23ad928304c8d0273eb065057456010cff13e2b6044570dbf26402e68075979d0
  db_user_name: <%= ENV["SBOX_DB_USER_NAME"] %>
  db_password: <%= ENV["SBOX_DB_DEV_PASSWORD"] %>
test:
  secret_key_base: 9593d9d282db3be3208edf4ba231c11b834cf2081dfc3a7c065e2fb74848dc7dec090d42e75c5f7df0cf1be786ee6f6dd55c37767b5093240f6cbd301f244b87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
